### PR TITLE
Make mustache.mjs work with Deno

### PR DESCRIPTION
**Pull request by zekth**
Here is the working changes.
The first import had to be changed due to this: https://github.com/denoland/deno/pull/1065

Also just done what we discussed and it's working :)

### CODE REVIEW

**Comment by phillipj** [comment]
Hoorray great work! Tried `deno` for the first time now, and it surely is pretty sweet having the TypeScript compiler built-in 👍 

The CI failures seems to be related to eslint is still targeting `mustache.js` which is now actually the build output. It should be changed to target `mustache.mjs` instead. I'll fix that in my branch.

**Comment by phillipj** [comment]
Took the liberty of pushing back to your branch with some minor whitespace changes -- CI is now green 🎉 

Thanks a lot for looking into making this deno-friendly!

I'll merge your changes into my branch now, before taking a step back and double checking a few things before opening the PR to upstream mustache.js.

**Comment by zekth** [comment]
Great!

**Comment by phillipj** [comment]
@zekth I really want to ensure deno works with mustache going forward by having a CI job run a trivial test. Ideally I'd like `deno` to exit with status > 0 to signal a test failure, but my tests locally always exist with status 0. Got any protips up your sleeve?

```ts
import { test } from "https://deno.land/std/testing/mod.ts";
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";
import mustache from "../../mustache.mjs";

const view = {
  title: "Joe",
  calc: function() {
    return 2 + 4;
  }
};

test(function canUseMustache() {
  assertEquals(
    mustache.render("{{title}} spends {{calc}}", view),
    "Joe spends 6"
  );
});
```

I've introduced a bug locally to trigger TypeScript compile error:

```
$ deno test deno-test.ts
Compile file:///..../test/module-systems/deno-test.ts
error TS2552: Cannot find name 'object'. Did you mean 'Object'?

► file:///..../mustache.mjs:11:30

11   return objectToString.call(object) === '[object Array]';
                                ~~~~~~

  'Object' is declared here.

    ► $asset$/lib.es5.d.ts:267:13

    267 declare var Object: ObjectConstructor;
                    ~~~~~~


$ echo $!
0
```

Sadly that won't do much good in CI :/ At first glance there's no `deno` CLI argument that will make it explode on TS errors / test failures?

**Comment by phillipj** [comment]
Nevermind, found the blooper; should have checked the exit code with `echo $?` instead of `echo $!`. Luckily it works as I was hoping for with that sorted out.

**Comment by phillipj** [comment]
For ref;

- Successful: https://github.com/phillipj/mustache.js/runs/268192472
- Broken: https://github.com/phillipj/mustache.js/runs/268195090

**Comment by zekth** [comment]
Also there is a Deno Github action if you want : https://github.com/denolib/deno-action

**Comment by phillipj** [comment]
Ahh cool! Google suggested https://github.com/denolib/setup-deno, but that deno-action alternative might be better for all I know 🤷‍♂

**Comment by zekth** [comment]
There is an improvement on the exposure of properties on importing json files : https://github.com/denoland/deno/pull/3210

**Comment by phillipj** [comment]
Oh cool! Will give that a shot before opening the PR to the upstream mustache.js repo.

**Pull request merged**
